import { ReactNode } from "react";
import Header from "@/components/common/Header";
import Head from "next/head";
import { Flex, Text } from "@chakra-ui/react";

export default function Layout({
  children,
  title,
}: {
  children: ReactNode;
  title: string;
}): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Flex direction="column" marginTop={20} gap="32px" padding={8}>
          <Text
            as="h1"
            fontSize={{ base: "xl", md: "2xl", lg: "3xl" }}
            fontWeight="bold"
            textAlign={{ base: "center", md: "start" }}
          >
            {title}
          </Text>
          {children}
        </Flex>
      </main>
    </>
  );
}
