import { ReactNode } from "react";
import Image from "next/image";
import styles from "@/components/common/Layout/style.module.css";
import Header from "@/components/common/Header";
import Head from "next/head";

export default function Layout({
  children,
  title,
}: {
  children: ReactNode;
  title: string;
}): JSX.Element {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className={styles.container}>
          <h1>{title}</h1>
          {children}
        </div>
      </main>
    </>
  );
}
